RepositoryPatternMVC/Models/Emp.cs
using System.ComponentModel.DataAnnotations;
namespace RepositoryPatternMVC.Models
{
    public class Emp
    {
        [Required(ErrorMessage="Id is required")]
        //[Range(1,100,ErrorMessage ="Id must be between 1-100")]
        public int Id { get; set; }

        [Required(ErrorMessage = "Name is required")]
        //[StringLength(20,MinimumLength =10,ErrorMessage ="lenght should be between 10 and 20")]
        //[RegularExpression(@"^S.*", ErrorMessage = "Name should start with S")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Salary is required")]       
        public double Salary {  get; set; }
    }
}

RepositoryPatternMVC/Models/ErrorViewModel.cs
namespace RepositoryPatternMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RepositoryPatternMVC/Controllers/EmpController.cs
using Microsoft.AspNetCore.Mvc;
using RepositoryPatternMVC.Models;
using RepositoryPatternMVC.Repo;
namespace RepositoryPatternMVC.Controllers
{
    public class EmpController : Controller
    {
        private readonly EmpRepo repo;
        public EmpController(EmpRepo repo)
        {
            this.repo = repo;
        }
        public IActionResult Index()
        {
            var dt=repo.GetAllEmps();
            return View(dt);
        }
      
        public IActionResult AddEmp()
        {          
            return View();
       
        }
        [HttpPost]
        public IActionResult AddEmp(Emp e)
        {
            if (ModelState.IsValid)
            {
                repo.NewEmp(e);
                TempData["msg"] = "Emp Added Successfully";
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }           
        }

        public IActionResult EditEmp(int id)
        {
            var employee = repo.GetEmpById(id);
            if (employee == null)
            {
                return NotFound();
            }
            return View(employee);
        }

        [HttpPost]
        public IActionResult EditEmp(Emp e)
        {
            if (ModelState.IsValid)
            {
                repo.ModifyEmp(e);
                TempData["msg"] = "Employee updated successfully.";
                return RedirectToAction("Index");
            }
            return View(e);
        }
        public IActionResult DeleteEmp(int id)
        {
            repo.RemoveEmp(id);
            return RedirectToAction("Index");
        }

        public IActionResult SearchEmp(string searchTerm, bool backToList = false)
        {
            if (backToList)
            {
                return RedirectToAction("Index");
            }

            var employees = repo.SearchEmp(searchTerm);
            return View("Index", employees);
        }
    }
}

RepositoryPatternMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RepositoryPatternMVC.Models;
using System.Diagnostics;

namespace RepositoryPatternMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RepositoryPatternMVC/Views/Emp/AddEmp.cshtml
@{
    ViewData["Title"] = "AddEmp";
}

@model Emp

<h1>AddEmp</h1>


<form method="post">
    
    <div class="form-group">
        <label for="exampleInputPassword1">Name</label>
        <input type="text" asp-for="Name" class="form-control" id="exampleInputPassword1" placeholder="enter name">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Salary</label>
        <input type="text" asp-for="Salary" class="form-control" id="exampleInputPassword1" placeholder="enter salary">
        <span asp-validation-for="Salary" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

@section scripts {
    <partial name="_ValidationScriptsPartial"></partial>
}

RepositoryPatternMVC/Views/Emp/EditEmp.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model RepositoryPatternMVC.Models.Emp

@{
    ViewData["Title"] = "Edit Employee";
}

<h1>Edit Employee</h1>

<h4>Employee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" asp-action="EditEmp">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" readonly class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="Salary" class="control-label"></label>
                <input asp-for="Salary" class="form-control" />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

RepositoryPatternMVC/Views/Emp/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Index";
}
@model List<Emp>

<h1>Index</h1>

@if (TempData["msg"] != null)
{
    @TempData["msg"];
}
<hr />
<form method="get" asp-action="SearchEmp" class="form-inline mb-3">
    <div class="form-group">
        <input type="text" name="searchTerm" class="form-control mr-2" placeholder="Search here" style="width: 200px;" />
    </div>
    <button type="submit" class="btn btn-sm btn-secondary mr-2">Search</button>
    <button type="submit" name="backToList" value="true" class="btn btn-sm btn-secondary">Back to List</button>
</form>

<a asp-controller="Emp" asp-action="AddEmp" method="post" class="btn btn-info">Add New Employee</a>
<br />
<table border="1" class="table">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Name</th>
            <th scope="col">Salary</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var emp in Model)
        {
            <tr>
                <td>@emp.Id</td>
                <td>@emp.Name</td>
                <td>@emp.Salary</td>
                <td>
                    <a asp-controller="Emp" asp-action="DeleteEmp" asp-route-id="@emp.Id" class="btn btn-danger">Delete</a>
                    <a asp-controller="Emp" asp-action="EditEmp" asp-route-id="@emp.Id" class="btn btn-success">Edit</a>
                </td>
            </tr>
        }
    </tbody>
</table>

RepositoryPatternMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

RepositoryPatternMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RepositoryPatternMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RepositoryPatternMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RepositoryPatternMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - RepositoryPatternMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>